(defproject gh "0.1.0-SNAPSHOT"
  :description "FIXME: write description"
  :url "http://example.com/FIXME"
  :license {:name "Eclipse Public License"
            :url "http://www.eclipse.org/legal/epl-v10.html"}
  :dependencies [[org.clojure/clojure "1.5.1"]
                 [org.clojure/algo.generic "0.1.1"]
                 [clj-time "0.6.0"]
                 [org.clojure/data.priority-map "0.0.4"]
                 [org.clojure/data.json "0.2.4"]
                 [prismatic/plumbing "0.2.1"]
                 [incanter/incanter-core "1.5.4"]
                 [incanter/incanter-charts "1.5.4"]
                 [incanter/incanter-zoo "1.5.4"]
                 ;; [com.jmeeks/clj-web-crawler "0.1.0-SNAPSHOT"]
                 ;; [org.clojars.kjw/commons-httpclient "3.1"]
                 [net.mikera/core.matrix "0.20.0"]
                 ;; [org.clojure/data.csv "0.1.2"]
                 ;; [clojure-csv/clojure-csv "2.0.1"]
                 ;; [com.nuroko/nurokit "0.0.3"]
                 ;; [org.clojure/algo.generic "0.1.1"]
                 ;; [org.clojure/data.json "0.2.3"]
                 ;; [com.keminglabs/c2 "0.2.3"]
                 ;; [hiccup "1.0.4"]
                 ;; [cc.artifice/clj-ml "0.6.0-SNAPSHOT"]
                 ;; [org.clojure/tools.trace "0.7.6"]
                 ;; [clj-liblinear "0.1.0"]
                 ;; [org.clojure/data.generators "0.1.2"]
                 ;; [svm-clj "0.1.3"]
                 ;; [clatrix "0.3.0"]
                 ;; [org.apache.commons/commons-math3 "3.2"]
                 ;; [net.sf.jung/jung-api "2.0.1"]
                 ;; [net.sf.jung/jung-graph-impl "2.0.1"]
                 ;; [net.sf.jung/jung-algorithms "2.0.1"]
                 ;; [net.sf.jung/jung-algorithms "2.0.1"]
                 ;; [net.sf.jung/jung-visualization "2.0.1"]
                 ])
